### PR TITLE
Rename Arm -> ARM

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by matthchr** [comment]
This is purely just renames, no actual logic changes

**Comment by Porges** [comment]
@matthchr do you mind if I delay this until I merge my changes? I've renamed a few ARM-related items. (Worst case I can just recreate this PR afterwards.)

**Comment by matthchr** [comment]
How bad do you think the conflicts will be? I also have some stuff based on top of this... but possibly can try rebasing it, which shouldn't be too bad.

**Comment by Porges** [comment]
> How bad do you think the conflicts will be? I also have some stuff based on top of this... but possibly can try rebasing it, which shouldn't be too bad.

Okay, if you have stuff on it then go ahead :)

**Pull request merged**
