### PR TITLE
ResourceGroup needs defaulting webhook

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by matthchr** [comment]
This fixes the nightly live tests which were failing

**Review by babbageclunk — APPROVED** [review]
Looks great! I guess this is because ResourceGroup is a special case that isn't generated, right? For all the other types we autogenerate the same webhook.

**Comment by matthchr** [comment]
@babbageclunk - yea, and it only fails the live tests because the recording tests don't (currently) validate that the incoming request body is the same as it was before.

@Porges is there a way to make the recording tests check that?

**Comment by Porges** [comment]
@matthchr we could but will need to check how much of the replay-tests it breaks 😉

**Comment by matthchr** [comment]
@Porges Should I file an item for it? I would think it wouldn't break too many but maybe that's optimistic.

**Comment by matthchr** [comment]
Filed #363

**Pull request merged**
