### PR TITLE
Allow DefineFunc to define funcs without receiver

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Review by babbageclunk — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
I've got a nicer version of this in my Test Cases branch, should get the PR out this week.

**Review by theunrepentantgeek — CHANGES_REQUESTED** [review]
Probably best to compare contrast with my branch before we merge one or the other.

**Comment by matthchr** [comment]
@theunrepentantgeek - Take a look at https://github.com/Azure/k8s-infra/pull/312/files#r516265457 which I left on your PR. I think we can probably fold this PR into yours, main question I have is around merge timelines and if it'd be better to split some of the `astbuilder` stuff out of your PR into its own PR.

**Comment by theunrepentantgeek** [comment]
I've incorporated the extra check into #312

**Comment by matthchr** [comment]
Abandoning this in favor of #313

**Pull request closed without merging**
